version: '3'
services:
  qanary-component-qb-wikidata: # for building from source
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: "QB-Wikidata"
    network_mode: host # usage of ports also possible